### ISSUE TITLE
Small example file

### ISSUE THREAD

**Issue by Mailaender** [mzdb/mzdb-specs#2]
Hi, can you provide a small `test.mzDB` one can use for unit tests?

**Comment by david-bouyssie** [comment]
Hi.
You can use that one:
https://github.com/mzdb/mzdb-rs/blob/main/mzdb-rs/data/OVEMB150205_12.mzDB

Feel free to ask if something is unclear.

**Comment by Mailaender** [comment]
Can you make one with only 25 scans instead of several thousands? I tried to drop entries from `spectrum` but the file size is still 17 MB.

**Comment by david-bouyssie** [comment]
Well, if you have a specific raw file in mind I could run a conversion.
This one might be a good fit?
http://proteowizard.sourceforge.net/example_data/small.RAW

**Comment by david-bouyssie** [comment]
BTW, dropping entries from spectrum will not shrink the file size. The data are encoded in the bounding_box table, in a BLOB field.

**Comment by Mailaender** [comment]
> This one might be a good fit? http://proteowizard.sourceforge.net/example_data/small.RAW

Looks good. That one full scan is enough and the empty ones create a bit of retention time.

**Comment by Mailaender** [comment]
https://github.com/mzdb/mzdb-specs/tree/master/example_data
